### ISSUE TITLE
How to Change the Onboarding Sequence

### ISSUE THREAD

**Issue by codemonza** [SteveBarnegren/TweenKit#19]
Thank you for the work! The animation seems very easy to do! 

In the examples, how can I change the sequence of the animations? Tried to edit this in the OnboardingExampleViewController but it still doesn't change which animation comes first and so on. Pointers will be very appreciated!

```
 return ActionGroup(actions:
                [introAction,
                 rocketAction,
                 starsAction,
                 makeClockAction(),
                 makeTkAttributesAction(),
                 makeBackgroundColorsAction()]
            ) 
```

**Comment by SteveBarnegren** [comment]
Hi @codemonza 

If you want to run multiple actions with TweenKit there are two options, `ActionGroup` and `ActionSequence`. `ActionSequence` runs all of the actions in order one after the next, and `ActionGroup` runs all of the actions together at the same time.

For the onboarding example, intuitively it makes sense to use an `ActionSequence`, but in the end it didn't because the actions actually overlap each other. For instance, the clock animates over three slides, and the stars animate over one, but they also share one transition, so it's not possible to run them one after another.

Instead, I used an `ActionGroup` (the code you've pointed out), but some of the actions start with a delay.

For instance, in `makeClockAction()` once the whole action is built (`fullAction`), it's returned in a sequence with a 1 slide delay:

```
return ActionSequence(actions: DelayAction(duration: 1.0), fullAction)
```

This means that when it's played simultaneously with the other actions in the group, the clock animation does nothing for the first slide. If you remove the `DelayAction` or set the duration to `0.0`, then the clock animation will begin at the start, and overlap the rocket. You could then try to move the rocket to be later if you wanted to reorder them, by wrapping the `rocketAction` in an `ActionSequence` with a `DelayAction` at the start.

Does that help?

**Comment by codemonza** [comment]
Thank you so much, Steve!! This is so helpful! Yes I am able to move the animation around now :D
