### ISSUE TITLE
RepeatForeverAction.update(elapsedTime:) crash

### ISSUE THREAD

**Issue by hanweixing** [SteveBarnegren/TweenKit#28]
SDK version: TweenKit (1.0.1)
issue: Some iphone devices crashed report from Xcode-Window-Organizer-Crashes.
iOS version: 13.1.3，13.3，13.4.1，13.6，13.6.1，14.0 etc.
Screenshot is like below:
![截屏2020-09-23 下午5 42 51](https://user-images.githubusercontent.com/15372186/93996343-b62c5f00-fdc4-11ea-8b67-241d426e2581.png)

It is like that crashes happened at 
```let repeatNumber = Int(elapsedTime / action.duration)``` 
So  is it possible `action.duration` to be equal to zero? or other reasons?

I can not figure it out temporarily, hope you can help. 
Thank you very much.

**Comment by SteveBarnegren** [comment]
Hi @hanweixing 

Sorry about that 😅  - I think your divide by zero theory is a good one.

I did a quick test, and it looks like swift doesn't crash on divide by zero, but it produces a `nan` result. If you try to create an `Int` by passing in a `nan` value that does cause a crash though. So it's possible that `action.duration` is `0` so the result is `nan` and that is causing a crash when used to create the `Int`.

I'm still a little unsure on why the `action.duration` would be `0`, unless explicitly set to be and what the appropriate course of action would be in that case. I'll run a few tests and see if I can get it to crash myself, in which case I might be able to create a fix.

If you're able to share a snippet of code showing how you construct the action that is crashing that would be really helpful.

**Comment by SteveBarnegren** [comment]
Ok, so I think there's possibly two things going on.

Firstly, if an action with a duration of 0 is repeated forever, then a crash can occur. I don't think that you'd explicitly create an action with 0 duration, but it might be something that could happen if the duration was determined dynamically. There's a check for this case now.

Secondly, if the app is backgrounded for a significant enough amount of time whilst a repeating action is running, then when the user returns to the app a crash can occur. I have a feeling that this is the one that your users are seeing. It might be that you need to have the app backgrounded for several hours and then return to cause that crash, which is why you might not have come across it in your own testing (I haven't seen it myself).  I'm pausing the animations in the background now, which should resolve this.

Both of those crashes happen in that update method, so hopefully one of those fixes resolves the issue.

The pull request is https://github.com/SteveBarnegren/TweenKit/pull/29 if you want to take a look at the changes.

I've released a new version to CocoaPods, it's 1.0.3.

It would be great to get some feedback on if this resolves the issue once you've got a new release of your app out!

**Comment by hanweixing** [comment]
@SteveBarnegren Hi, sorry to reply now after a long holiday. I searched my crashes again, and found that most users got this error when switching foreground mode and background mode, so the second theory maybe the reason. And i have seen these code change in 1.0.3, it is wonderful work. I will apply 1.0.3 to my app. Thank you very much!
