### ISSUE TITLE
Enhancement - ZwischenzugAction / and repeat sequences / use in tableviewcells / collectionviews

### ISSUE THREAD

**Issue by johndpope** [SteveBarnegren/TweenKit#3]
Thanks for quick response Steve on previous ticket.
Heads up  - I made a lot of progress on my view rotating label.
Here's a peak.
https://drive.google.com/file/d/0B-w3I-xzXGu0eFZhTnVLaGNYS3c/view

a couple things from stand point of consuming the library

1) not sure if you play chess - but I need a way to have some action in between actions.
I looked into the scheduleAction but there was no blocks to inject some method. 
perhaps you could consider down the track adding such an ZwischenzugAction ? or exposing a block on ScheduledAction or document if it's already possible?.

2) I see there's a repeat method for actions. - 
I couldn't see how to do this on a sequence.

from my code class above 

I have this class 
https://gist.github.com/johndpope/4897dc5070abce8637886fe9310b9b1b#file-gistfile1-txt-L88

on last line - I simply want to call
let cycleSequence = ActionSequence(actions: moveLeft,bankLabelRight,cycleLeftAgain )
        scheduler.run(action: cycleSequence , repeat: forever) // <- keep looping 

3) also - I couldn't see how to remove scheduler actions on destruction of cells.
 seems like my cells in tableview are being recycled causing some havoc.

**Comment by johndpope** [comment]
2) this should be documented / added to readme / how to use in cells.

    deinit{
        scheduler.removeAll()
    }

3) fyi - I solved the repeat sequence by calling the same method - but I get this error forcing me to add types to method. 
<img width="915" alt="screen shot 2017-05-18 at 11 24 32 am" src="https://cloud.githubusercontent.com/assets/289994/26210078/98596f18-3bbc-11e7-8d66-d0afd80af2d1.png">

fixed it

<img width="867" alt="screen shot 2017-05-18 at 11 26 14 am" src="https://cloud.githubusercontent.com/assets/289994/26210168/d82283aa-3bbc-11e7-9e30-32bd76e97412.png">

**Comment by johndpope** [comment]
fyi - seems like library is not so happy when used in tableviews.

<img width="1226" alt="screen shot 2017-05-18 at 11 31 48 am" src="https://cloud.githubusercontent.com/assets/289994/26210471/a8615e6a-3bbd-11e7-826c-6bd5fa27a719.png">

**Comment by johndpope** [comment]
when I rip out the action to call method again - it resolves.

**Comment by SteveBarnegren** [comment]
You can use a 'RunBlock' action to add a callback to an 'ActionSequence'. Here's an example from one of my projects:

```
  let logoAction = makeLogoAction()
        let animateInAction = makeAnimateInAction()
        let peelAction = makePeelAction()
        let zoomAction = makeZoomAction()
        
        let endBlock = RunBlockAction { 
            [unowned self] in
            self.delegate?.canArtworkAnimationDidFinish()
        }
        
        let sequence = ActionSequence(actions:
            [logoAction,
             animateInAction,
             peelAction,
             zoomAction,
             endBlock,
            ])
```

I really need to document how to remove an action better. Basically, internally, the `ActionScheduler` wraps actions in an `Animation` class. When you run an action, you actually get it's `Animation` back if you want it.

![screen shot 2017-05-18 at 16 37 21](https://cloud.githubusercontent.com/assets/6288713/26210682/53360fd2-3be8-11e7-8fb5-c280d50229ab.png)

If you keep hold of that `Animation` object, then you can pass it to the scheduler, with the `remove(animation: Animation)` method and it will be removed.

If you're using it in a tableview cell, then it might just be that you need to be careful that the animation stops when the cell is recycled. Otherwise the callback will keep occurring. I guess that could cause a few issues.

**Comment by johndpope** [comment]
Thanks again Steve.

I love swift - I hooked into the protocol and hot wired it

        let cycleSequence = ActionSequence(actions: moveLeft,bankLabelRight,cycleLeftAgain )
        let repeatableSequence = cycleSequence.repeatedForever()
        scheduler.run(action: repeatableSequence)
        

   public extension ActionSequence {
    
        public func repeatedForever() -> RepeatForeverAction {
           return RepeatForeverAction(action: self)
       }
    }
