### ISSUE TITLE
Question: Can this be used to Animate from One image/UIVIew to another?

### ISSUE THREAD

**Issue by otymartin** [SteveBarnegren/TweenKit#5]
@SteveBarnegren 
This library looks super powerful. Based on how you animated the String by having "String" inherit `tweenable` protocol, I'm wondering if more complex objects such as `UIImageViews` can be animated?

**Comment by SteveBarnegren** [comment]
@otymartin Thanks for the interest in TweenKit!

In theory, you can animate any object, as long as you provide a `Tweenable` conformance that defines what it means to be at some point between two different instances of that type.

In practice, if the type that you are trying to animate is very complex, then it would be difficult (and slow) to animate between two instances, purely because there would be so many properties to animate. The other issue you would likely run in to is that there would be properties such as `enum`s and `bool`s that aren't continuous, so don't really animate very well.

So the conclusion that I've come to is that you should only make something conform to `Tweenable` if, given two instances of that type, it's obvious what if would mean to be at some point between the first and second instance.

There's a bunch of types where that is the case, `UIColor` is a good example. Between red and yellow is some shade of orange, and we can return a new interpolated colour calculating new `rgba` values.

If you wanted to animate between two views, you probably only need to animate the `alpha` property of those views. So you can reach in from the callback you get from `TweenKit` and interpolate those properties so that they transition from the first state to the second. Really, all your animating is a `CGFloat` (which conforms to `Tweenable` out of the box), and just setting it to the views alpha property.

Hope that helps!

**Comment by otymartin** [comment]
@SteveBarnegren 
Thanks for the detailed explanation Steve. I know I was reaching my usecase which technically I just want to be able to animate a change from a "Diamond shape` to a "Circle Shape" without diving into UIBezier's and layers so I thought imageViews would be easier.

But having said that I have a million other use cases for this library so Im really glad it exists.

Cheers :)

**Comment by SteveBarnegren** [comment]
@otymartin
You might be able to do it without using bezier paths at all. You can create a standard `CALayer` with a square shape to use as a mask, and rotate it 45 degrees to get a diamond.

Now you can animate a `CGFloat` with TweenKit, and set it as the corner radius of the layer. I don't think that the corner radius is animatable with `UIView` animations, although it actually looks like you could use `CABasicAnimation` and you wouldn't need to use TweenKit at all. https://stackoverflow.com/questions/5886915/animating-calayer-of-uiview-to-round-corners

If it turns out that you do need morph `UIBezierPaths`, then I think a library like TweenKit is probably the easiest way to go for that. You would just need to a function that produces the correct bezier path given a value between 0 and 1, and use to produce and apply the new path in the callback for the animation.

**Comment by otymartin** [comment]
@SteveBarnegren 
I thought of that technique at first but the problem is the diamond I want to animate is a very unique shape. its not a square. And the corner radius are not uniform on all sides. Im gonna wrestle with tweenkit see if I can animate the shape into a circle and back.

If your curious, I have a PaintCode output of the Diamond in this Gist https://gist.github.com/otymartin/3155eec6c4bc5ef15b40c9526a66bcb0
![diamonds1600](https://user-images.githubusercontent.com/2222881/32014514-4736ca60-b98c-11e7-9380-56e6f023dd3a.png)

**Comment by SteveBarnegren** [comment]
@otymartin 
That's pretty challenging! It's tough, because you only really need 4 curves to make the circle, but the diamond requires a bunch more. I haven't used Paintcode in a while, but I'm sure it allowed for some kind of extracted variables that you could use to animate a shape. If you had those you plug them in to an engine like TweenKit pretty easily.

You can take a look at this too if you want - [https://bitbucket.org/SteveBarnegren/beziermorph](https://bitbucket.org/SteveBarnegren/beziermorph) 

It's a project I made a while back that can morph between any two `UIBezierPath`s. It was just a demo really, so the code's a bit messy, but there's an example project that shows it in action. It's less performant than manipulating the path directly, because it breaks the paths down in to smaller sections, but it does do what you're after.

I love these kind of challenges! They take a while, but it's so satisfying when you crack it. Good luck!

**Comment by GoldenJoe** [comment]
I'd like to second this question. Suppose you want to change from one UIImage to another UIImage by a fade or perhaps a mask operation. How would you implement Tweenable?

**Comment by otymartin** [comment]
@SteveBarnegren 
Unfortunately can't play with your beziermorph lib since its in Objective C 😅 but I'll use a converter and see if I can get the swift version. it looks super promising. I do agree the challenge is quite interesting, and fulfilling once you pull it off. There are a lot of techniques to fake the same animation but none quite like the real deal so its with the struggle.
Thanks so much for the pointers.
Also Good question above, I'd like to know that too.

**Comment by SteveBarnegren** [comment]
@GoldenJoe 
In this case, you don't really need to deal with the `Tweenable` protocol. In fact, it's only for fairly advanced use cases where you need to implement it yourself.

So if you wanted to fade from one UIImage to another, I would create a UIView subclass that contains two UIImageViews. You could then create a method that fades between the two of them, for instance `fadeTo(pct: CGFloat)` that internally sets the alpha property of the two image views to blend them. (Depending on how you want it too look, you could just fade the top one)

You're really only dealing with the CGFloat that you pass in here, and CGFloat adopts `Tweenable` out of the box, so you don't need to implement `Tweenable` yourself. If you want to do a complex animation, like chaining, or scrubbing, then TweenKit would be a good option, but if you just want a basic fade, then UIView animations will do the trick.

**Comment by GoldenJoe** [comment]
Thanks for the fast reply, Steve. Subclassing was the idea I had too, but I wasn't quite clear on the implementation. Do you intend for us to extend classes so that we can say something like:

```
let iv = MyCustomDualImageView()
        let action = InterpolationAction(from: { [unowned self] in self.iv.imageA },
                                         to: imageB,
                                         duration: 2,
                                         easing: .exponentialInOut,
                                         update: )
```
Or to set values in the update closure, like:

```
let iv = MyCustomDualImageView()
        let action = InterpolationAction(from: { [unowned self] in self.iv.progress },
                                         to: 1,
                                         duration: 2,
                                         easing: .exponentialInOut,
                                         update: { [unowned self] in self.iv.progress = $0 })
```

I was just thinking, that it may be more convenient in some cases to make the property itself animatable, particularly if it is something you are going to reuse, but it's not clear how you would actually do that. If it's not the intended design, the second way is still very simple. I suppose as a third way, you could write a little animation factory in the custom class that basically wraps the second method. What's your intention?

**Comment by SteveBarnegren** [comment]
@GoldenJoe 
I'd go with the the second one. I'm not sure how the first example would work, if you're tweening a `UIImage` then you would need to make `UIImage` conform to`Tweenable`. That would rely on you creating a method that could return a new `UIImage` that was part way between one instance and another.

That's definitely possible, and probably actually has some cool niche uses, but would be a really expensive way to make a fade, as you would be creating a new image each time. In the second example, you're just creating a new `CGFloat` for each update, which is cheap.

**Comment by GoldenJoe** [comment]
Yeah, I solved it the second way since it seemed like that's what you intended. While I was using it, I wrote a little factory extension for UIView using KVC:

```
extension UIView
{
    func makeAction<T: Tweenable>(keyPath kp: ReferenceWritableKeyPath<UIView, T>, toVal: T, duration: CFTimeInterval = 1.0, easing: Easing = .sineInOut) -> InterpolationAction<T>
    {
        let action = InterpolationAction(from: self[keyPath: kp],
                                         to: toVal,
                                         duration: duration,
                                         easing: easing) { self[keyPath: kp] = $0 }
        return action
    }
}
```

You use it like:

`let a = myView.makeAction(keyPath: \UIView.alpha, toVal: 1.0)`

Pretty easy to read, huh? There's just one small caveat - it only works for UIView keypaths (alpha, frame, layer.cornerRadius, etc). If you subclass UIView with a Tweenable property, you need to make a new extension for that class. Any idea how to wrap that all into one extension? Do you have any interest in adding a factory method like this to the project?

**Comment by SteveBarnegren** [comment]
This is a cool idea. I really like how you both read the initial value and set the new value using the key path. I tried to allow for a similar thing with the 'from' closure, but it's a bit ugly, because you have to return the value you want to animate from within the closure.

In your example it looks like you're reading the from value at the point that the action is made, but you could actually wrap it in a closure and you would be able to read it at the time that it's run instead, but with the same api that you have now. (that might turn out to be a bit flakey, but we could try it)

That would be cool, because for most users it makes more sense to them for the a value to animate from its current value to a new value, not from the value it was when the action was defined.

So I like it, but I don't like the ties with UIKit. Ultimately I'd like to keep all ties with specific frameworks at a minimum, so that I can easily port to AppKit when I need to, or work with some other UI system (say, SpriteKit).

I haven't really worked with key paths much yet, but I wonder it it would be possible to have an `init` method on `InterpolationAction` that takes an object, keypath, and value? That way you can animate any key path of any object?
