### ISSUE TITLE
Can you run an animation as an animation, then interrupt and scrub through it?

### ISSUE THREAD

**Issue by GoldenJoe** [SteveBarnegren/TweenKit#6]
Wondering if there is a way to combine the scheduler and scrubber.

**Comment by SteveBarnegren** [comment]
This is a really cool idea actually, it's not a use case that I'd thought about. I'm not sure that this is that simple to do out of the box with the current functionality, it's really either scheduled or scrubbed at the moment.

I'm not sure what the api for this would look like, but I'll have a think about it. It would be a cool feature to have, so if I have time I might try to include it. If you have any ideas for how you think it might work then let me know.

In the meantime, one work around is that you can setup your own `CADisplayLink` and use that to drive the ActionScrubber`. Than you can switch between using the display link / scrubbing to drive the animation.

**Comment by GoldenJoe** [comment]
Thanks. I'll think about it too. Maybe when an ActionScheduler is interrupted, its Actions get copied to an instance ActionScrubber?

**Comment by GoldenJoe** [comment]
Conversely, I can see a use for a "snap" behavior, where you animate to the start or end of a scrubber, like when the user stops dragging. Would you be around to take some time to chat this week? I like this library...it's like an expanded version of something I wrote, but it's missing a few things I had, partially due to the added complexity. I want to see if I can help you beef this up and make it _perfect_.

**Comment by SteveBarnegren** [comment]
@GoldenJoe It's actually quite a tricky issue to resolve in a way that doesn't negatively impact the usage when you're not mixing scheduling / scrubbing.

When I have a bit of time, I might create another example in the example application that I can use to play around with some apis for this use case

It might be that the scrubber can have some sort of 'auto-scrub' feature, where it essentially drives it's animation with a scheduler. There's some additional complexity to handle there, because the scrubber infers the direction of the animations from the values it receives, and schedulers only run animations in a forwards direction. I think we could make it work though.

Sure, you're welcome to send me an email. My email address is public on my github profile, or you can use the contact form on my website [website](www.stevebarnegren.com)
