### ISSUE TITLE
Should ActionScheduler's animations property be public?

### ISSUE THREAD

**Issue by GoldenJoe** [SteveBarnegren/TweenKit#7]
While implementing a "snap" animation, I came across a minor issue. I'd like to prevent a new snap animation from being scheduled before the previous has finished. I simply cancel the previous animation when scheduling a new one:

```
if let snapAnim = snapAnim
{
    tkScheduler.remove(animation: snapAnim)
}
```

However, if the animation has already played out, I get an error in console: "Can't find animation to remove". It would be convenient if I could check to see if the scheduler already contains an animation in order to avoid the message. Not sure if you'd rather expose the `animations` property or implement a `contains` method. I can do either.

**Comment by SteveBarnegren** [comment]
I think this is probably quite a common use case, so I agree that we should come up with a fix!

We could maybe make the `animations` property public (but with a private setter), so that the user can inspect the animations if the want (they could keep a reference to them when they're created anyway, so they're not really private).

I think it's also safe to remove that error message too, so that if the user tries to remove an animation that isn't currently active in the scheduler, then nothing will happen.

Do you want to make a PR for it, and then you can check that it works in the context of your project? If not, I can make the changes, but it might have to be next week some time.

If you do make any changes, make sure you branch / merge back to development.

**Comment by SteveBarnegren** [comment]
Oops, reopened.
